### ISSUE TITLE
Redis connection using sentinels ...

### ISSUE THREAD

**Issue by manojsanthakumaran** [hootsuite/akka-persistence-redis#17]
Hi,

This is not an issue report, but a feature request.

I was trying to integrate this plugin in my project, where I have three sentinels in-front of three Redis cluster nodes (1 master, 2 slaves), for fail-over.
This feature is not currently supported by this plugin, would like to know whether this is there in your roadmap?

Thank you very much.
Manoj

**Comment by ssong-van** [comment]
Hi Manoj, 

Have you tried 0.5.0 that exposes Sentinel configs?

```
redis {
  host = "localhost"
  port = 6379
  sentinel = false
  #sentinel-master = "mymaster"
  #sentinels = [{host :"localhost", port: 26379}]
}
```

**Comment by manojsanthakumaran** [comment]
Hi Steve,

Regret that I missed to notice your recent commits !!

Indeed 0.5.0 works perfectly fine with sentinel configurations. I tested it today with my three sentinels and worked as expected.

Hearty appreciate you for bringing such a useful plugin, and your quick reply.

Thank you very much.
Manoj

**Comment by ssong-van** [comment]
Awesome, glad to hear it works. Credit should go to @Pritesh-Patel who submitted the Sentinel work. I'll close this ticket.

**Comment by l15k4** [comment]
Hey,

I'm using Redis on aws ElastiCache which doesn't use Sentinel I guess.
Even though I have a HA Redis cluster, I'm not sure that the way akka-persistence-redis connects to it using `RedisClient` makes it fault tolerant. Do you guys have any pointers?

**Comment by hootsuitemike** [comment]
@l15k4 No there's no Sentinel support in ElastiCache (or at least there wasn't a year ago when we were looking at this). We use https://github.com/twitter/twemproxy in production to safely fail over to the new master during a master swap.
