### ISSUE TITLE
Redis persist to disk not working

### ISSUE THREAD

**Issue by yadavan88** [hootsuite/akka-persistence-redis#18]
I am using `embedded-redis` with `akka-persistence-redis`. The snapshot and journals are getting saved to the redis. However, if the machine is restarted, the data is getting lost. For that I have configured the redis to take automatic dump and persist to disk. It is working fine, if I try with redis (without akka-persistence-redis). However, when I apply akka-persistence-redis, the dump file is not getting created. What am I doing wrong ?

**Comment by yadavan88** [comment]
Sorry, my mistake. The folder path I had given was wrong.

**Comment by ssong-van** [comment]
Great, glad to hear it's working.
