### ISSUE TITLE
Deploying to central maven repo

### ISSUE THREAD

**Issue by AnirudhVyas** [hootsuite/akka-persistence-redis#19]
Can this be deployed to akka central repository?

**Comment by ssong-van** [comment]
For sure, we will sign up for Maven Central account. Stay tuned!

**Comment by hveiga** [comment]
Any update on this?

**Comment by ssong-van** [comment]
Sorry for the delay. We now have Sonatype account. We'll publish to Maven Central this week.

**Comment by ssong-van** [comment]
0.7.2 is now available on Maven Central. 
```
<dependency>
  <groupId>com.hootsuite</groupId>
  <artifactId>akka-persistence-redis_2.12</artifactId>
  <version>0.7.2</version>
</dependency>
```

**Comment by AnirudhVyas** [comment]
Haa thanks!!
