### ISSUE TITLE
Needed some additional setup

### ISSUE THREAD

**Issue by justinhj** [hootsuite/akka-persistence-redis#2]
I got this working and it seems pretty cool. There were some extra steps to go through to get it working.

In the instructions the version number to put in the build.sbt is 0.1.0 but in the repository it is 0.0.1

concretely "com.hootsuite" %% "akka-persistence-redis" % "0.0.1"

I had to add the redis dependency

resolvers += "rediscala" at "http://dl.bintray.com/etaty/maven"

libraryDependencies ++= Seq(
  "com.etaty.rediscala" %% "rediscala" % "1.5.0"
)

I had to paste the akka-persistence config into my own for it to find it

**Comment by ssongvan** [comment]
Thank you for the comment. Kudos to digging in deep to get it working! 

0.1.0 was released on Sep 30 and I am guessing you tried this before the release date. Is this true? Have you tried 0.1.0 recently?

I didn't think you would need to specify rediscala dependency manually. Let me dig more into this.

**Comment by ssongvan** [comment]
@justinhj I learned that scope of resolver in plugins.sbt is limited to plugins so build.sbt needs the resolver. I've created a PR for it if you would like to give it a review.

**Comment by justinhj** [comment]
Hi 

PR looks good to me.

**Comment by ssong-van** [comment]
Resolved in 0.2.1
