### ISSUE TITLE
Support redis db selection

### ISSUE THREAD

**Issue by focusj** [hootsuite/akka-persistence-redis#24]
Recently, I import akka-persistence-redis in my project, but i found that it does not support db selection. Do you have play to support it?

**Comment by hootsuitemike** [comment]
Hi, I don't understand. Can you give more information about what you mean by "db selection".

**Comment by focusj** [comment]
Sorry about my poorly English. db selection is Redis database select functionality.

My situation is our whole team share one Redis server, each project use one database. 
My project has no right to use db 0. I try to make the Redis configuration like this,
```
redis {
  host = "localhost"
  port = 6380
  db = 2
}
```
but it still save journal data in db 0.

**Comment by hootsuitemike** [comment]
Does the Redis client we are using support db selection? If so, we would appreciate a PR to add support!

**Comment by ssong-van** [comment]
rediscala has `SELECT index`. You could probably send this command after initializing RedisClient to select db2. We always welcome a PR!

**Comment by focusj** [comment]
RedisClient & SentinelMonitoredRedisClient has a constructor parameter `db` with type Option[Int]. So, if it has value so RedisClient will use db you configured, and if it is None, RedisClient will use db 0. I will push my pr soon.

**Comment by focusj** [comment]
Here is the [pr](https://github.com/hootsuite/akka-persistence-redis/pull/29), plz help review.

**Comment by ssong-van** [comment]
Thank you very much for the PR. Just released 0.7.1
