### ISSUE TITLE
What is the exact maven repository link?

### ISSUE THREAD

**Issue by yhdai** [hootsuite/akka-persistence-redis#28]
I can't find it in repo1.maven.org/maven2/.

**Comment by ssong-van** [comment]
The project is not published to Maven yet. We are actively working to publish to both Bintray and Maven so stay tuned!

**Comment by ssong-van** [comment]
Sorry for the delay. We now have Sonatype account. We'll publish to Maven Central this week.

**Comment by ssong-van** [comment]
0.7.2 is now available on Maven Central. 
```
<dependency>
  <groupId>com.hootsuite</groupId>
  <artifactId>akka-persistence-redis_2.12</artifactId>
  <version>0.7.2</version>
</dependency>
```
