### ISSUE TITLE
Cannot resolve rediscala dependency

### ISSUE THREAD

**Issue by robfletcher** [hootsuite/akka-persistence-redis#4]
When I try to build the project I get the following error:

    sbt.ResolveException: unresolved dependency: com.etaty.rediscala#rediscala_2.11;1.4.0: not found

I can resolve it by adding this to `build.sbt`:

    resolvers += Resolver.jcenterRepo

**Comment by ssongvan** [comment]
Just to clarify, are you building your own project with this plugin as opposed to compiling the plugin? `resolvers += Resolver.jcenterRepo` is already added to https://github.com/hootsuite/akka-persistence-redis/blob/master/project/plugins.sbt for this project to compile. If the error is from your own project, I will update README.

**Comment by robfletcher** [comment]
No, I was just trying to build this project in the process of working on a pull request.

**Comment by ssongvan** [comment]
@robfletcher I figured out that things just worked for me because of local ivy cache and maven proxy at work. I've made a PR that adds jCenter resolver in build.sbt which should fix the issue. Please review and I will release it under 0.2.1.

**Comment by robfletcher** [comment]
That works for me.

**Comment by ssong-van** [comment]
Resolved in 0.2.1
