### ISSUE TITLE
Journal query interface implementation ?

### ISSUE THREAD

**Issue by epot** [hootsuite/akka-persistence-redis#41]
Hey,

I am not sure what are your plans regarding this great plugin, but I recently had to migrate to https://github.com/safety-data/akka-persistence-redis because I needed the journal query implementation. Are there any plans to offer this in this plugin? Or to abandon it in favour of the other one?

Thanks!

**Comment by ssong-van** [comment]
Hi, we welcome PRs as always and try our best to response as quickly as possible. That said, we don't have plans on updating the plugin.

**Comment by epot** [comment]
Ok thanks, as the other one seems recommended by Akka and offer what I need, I am going to migrate to it.
